# Generated by Django 5.0 on 2023-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishings", "0003_action_created_at_phishing_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="id",
            field=models.CharField(
                default=None,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="id",
            field=models.CharField(
                default=None,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
