# Generated by Django 5.0 on 2024-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishings", "0004_alter_form_id_alter_input_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="phishing",
            name="url",
            field=models.URLField(max_length=512),
        ),
    ]
