# Generated by Django 5.0 on 2024-01-15 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phishings", "0006_form_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="page",
        ),
    ]
